apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: instance 
  namespace: openshift-logging
spec:
  managementState: Managed 
  logStore:
    type: lokistack
    lokistack:
      name: logging-loki
