apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    cluster.ocs.openshift.io/local-devices: "true"
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  encryption:
    clusterWide: true
    enable: true
  managedResources:
    cephBlockPools:
      defaultStorageClass: true
    cephRBDMirror:
      daemonCount: 1
  nfs:
    enable: false
  storageDeviceSets:
  - config: {}
    count: 7
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1"
        storageClassName: local-ssd
        volumeMode: Block
      status: {}
    name: ocs-deviceset-local-ssd
    placement: {}
    preparePlacement: {}
    replica: 3
    resources: {}
