apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: compute-resources
  namespace: quota-demo
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
