apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: compute-limits
  namespace: quota-demo
spec:
  limits:
  - type: Container
    max:
      cpu: 500m
      memory: 500Mi
    min:
      cpu: 100m
      memory: 100Mi
    default:
      cpu: 200m
      memory: 200Mi
