apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: core-object-counts
  namespace: quota-demo
spec:
  hard:
    configmaps: "4" 
    persistentvolumeclaims: "3" 
    replicationcontrollers: "20" 
    secrets: "4" 
    services: "1" 
    services.loadbalancers: "1" 
