apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: storage-consumption
  namespace: quota-demo
spec:
  hard:
    persistentvolumeclaims: "9"
    requests.storage: "60Gi"
